### ISSUE TITLE
Suggestion to rearrange VAT field usage

### ISSUE THREAD

**Issue by fixundfertig123** [alyf-de/erpnext_germany#31]
Hello everyone.

Trying to get in ERPNext and being from Germany I found this app. That's a great help. Thank you for all your work!!!

I came across a problem of the current VAT field usage and I hope I used the app correctly. Please excuse if I misunderstood something! Having a slight IT and business background I would suggest to the VAT field to every customer, supplier and company (in the registration field) and loose couple those to the VAT ID check. Since a VAT ID can be added and revoked from customers and supplier at any point this in later terms would ease purchase orders, sales orders, ... 

However, I am not yet fit in terms of the patch structure of Frappe (ensuring backward compatibility) so I created a forked branch: [https://github.com/fixundfertig123/erpnext_germany/tree/pu/changeRequest/vat](https://github.com/fixundfertig123/erpnext_germany/tree/pu/changeRequest/vat)

This change request would in parts picks up the problem addressed at #29. 

Please ask any question there are.

Kind regards

**Comment by barredterra** [comment]
This has been discussed before, please see #15

**Comment by fixundfertig123** [comment]
Hi @barredterra, thank you for your quick reply and pointing to this closed issue. I indeed did not see it. 

To be honest I do not favor to allow multiple meanings in one field and leave the decision to the end user. From my experience this can cause a small data integrity disaster. In particular since both - Tax-ID and VAT-ID - are simply to different numbers, to my knowledge even in the US, UK and France. Therefore they should be treated individually to allow users to use them where they need them. For example I stumbled upon this issue when tried to use both of them in custom exports, letterheads, ... And this problem might even increase if other new international tax ids like TIN might need to be added.

This ERPNext app is great and is tailored to address German "accounting issues", therefore I - and obviously others as well - see a benefit to store both number separately. But I see your point and from my basic knowledge about ERPNext and this app I can see that splitting these number fields up into two could cause some severe problems upon existing installations. So the backwards compatibility would need to be ensured. Therefore my general questions: Would you in general be open for this design change and if so, what are you main concerns I would have to consider?

**Comment by fixundfertig123** [comment]
Hi. In terms of my planing I would allow myself to kindly ask, if there is a rough indication / tendency regarding my question.

**Comment by barredterra** [comment]
At the moment, I honestly don't see strong reasons to do this. It's a lot of effort and the benefits are unclear. In all implementations I've done, this was never a requirement.

**Comment by fixundfertig123** [comment]
Hi, I absolutely understand your point of you. Unfortunately since I need it (and since others indicated there need as well) I will branch it in my forked repo and merge your updates into mine. I hope this is fine to you. Maybe it will clarify down the road.
